# Generated by Django 3.2.25 on 2025-08-11 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='mileage',
            new_name='km_driven',
        ),
        migrations.RemoveField(
            model_name='car',
            name='make',
        ),
        migrations.AddField(
            model_name='car',
            name='city',
            field=models.CharField(default='Ahmedabad', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car',
            name='owner_type',
            field=models.CharField(choices=[('1st', '1st Owner'), ('2nd', '2nd Owner'), ['3rd', '3rd Owner']], default='1st Owner', max_length=20),
        ),
    ]
