# Generated by Django 3.2.25 on 2025-08-11 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20250811_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='owner_type',
            field=models.CharField(choices=[('1st', '1st Owner'), ('2nd', '2nd Owner'), ('3rd', '3rd Owner')], default='1st Owner', max_length=20),
        ),
    ]
