# Generated by Django 3.2.25 on 2025-08-11 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_car_owner_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carimage',
            name='image_url',
            field=models.ImageField(upload_to='car_images/'),
        ),
    ]
