# Generated by Django 3.2.25 on 2025-08-11 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_car_owner_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='brand',
            field=models.CharField(default='Mercedes', max_length=50),
            preserve_default=False,
        ),
    ]
